import Link from "next/link";
import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, MoveUpRight, Plus, ShieldCheck, Sparkles, Users } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { getProducts } from "@/lib/wordpress";

export default async function Home() {
  const products = await getProducts();
  return <>
    <section className="home-hero">
      <Image src="/images/tabeer-hero.png" alt="Athletes in teal and black team uniforms" fill priority sizes="100vw" className="hero-image" />
      <div className="hero-shade" />
      <div className="container hero-content">
        <div className="hero-copy"><span className="eyebrow hero-eyebrow"><span className="eyebrow-line" /> THE GAME STARTS HERE</span><h1>BUILT FOR<br /><em>EVERY</em> GAME<span className="hero-dot">.</span></h1><p>Custom teamwear and sports essentials with the energy to match your ambition.</p><div className="hero-actions"><Link href="/products" className="btn btn-teal">Explore products <ArrowUpRight size={19} /></Link><Link href="/about" className="btn btn-ghost">Discover our story <ArrowRight size={18} /></Link></div></div>
        <a className="hero-scroll" href="#intro"><span>SCROLL TO EXPLORE</span><ArrowDown size={17} /></a>
      </div>
      <div className="hero-side-label">TABEER SPORTZ / PERFORMANCE IN MOTION</div>
    </section>

    <section className="ticker" aria-label="Products we create"><div className="ticker-track">{Array.from({ length: 2 }).map((_, i) => <span key={i}>UNIFORMS <b>✳</b> TEAMWEAR <b>✳</b> EQUIPMENT <b>✳</b> BUILT TO PLAY <b>✳</b> </span>)}</div></section>

    <section id="intro" className="section intro-section container"><div className="section-kicker"><span className="tiny-square" /> ABOUT TABEER SPORTZ</div><div className="intro-grid"><h2 className="display-heading">THE RIGHT GEAR<br />CHANGES <span>EVERYTHING.</span></h2><div className="intro-side"><p>Every team has an identity. We help bring it to life through sports uniforms, apparel and equipment designed to look as ready as you feel.</p><Link href="/about" className="text-link">More about us <ArrowUpRight size={18} /></Link></div></div></section>

    <section className="section collections-section"><div className="container"><div className="section-heading-row"><div><div className="section-kicker"><span className="tiny-square" /> THE COLLECTION</div><h2 className="display-heading">GEAR FOR <span>YOUR GAME.</span></h2></div><Link href="/products" className="text-link desktop-link">View all 13 products <ArrowUpRight size={18} /></Link></div><div className="featured-grid">{products.slice(0, 6).map((product, index) => <ProductCard key={product.slug} product={product} index={index} />)}</div><Link href="/products" className="btn btn-outline mobile-all">View all products <ArrowUpRight size={17} /></Link></div></section>

    <section className="statement-section"><div className="container statement-inner"><div><div className="section-kicker section-kicker-light"><span className="tiny-square" /> WHY TABEER SPORTZ</div><h2>ONE TEAM.<br /><span>ONE VISION.</span><br />EVERY DETAIL.</h2></div><div className="statement-side"><p>From the first concept to the final whistle, the details make the difference. Find a complete range for teams, clubs and athletes in one place.</p><Link href="/contact" className="round-link" aria-label="Start an inquiry"><ArrowUpRight size={30} /></Link></div></div><span className="statement-watermark">TS</span></section>

    <section className="section journey-section"><div className="container"><div className="section-heading-row journey-heading"><div><div className="section-kicker"><span className="tiny-square" /> YOUR TEAM, YOUR WAY</div><h2 className="display-heading">FROM IDEA TO<br /><span>GAME DAY.</span></h2></div><p>Starting something for your team? Here is a simple way to begin the conversation.</p></div><div className="journey-grid"><div className="journey-card"><span className="journey-index">01 <span>—</span> EXPLORE</span><div className="journey-graphic journey-graphic-one" aria-hidden="true"><span>01</span></div><h3>Find your fit</h3><p>Browse the range and choose the uniforms, apparel or gear your team needs.</p></div><div className="journey-card"><span className="journey-index">02 <span>—</span> SHARE</span><div className="journey-graphic journey-graphic-two" aria-hidden="true"><span>TS</span></div><h3>Make it yours</h3><p>Tell us your colors, team details, quantities and ideas for customization.</p></div><div className="journey-card"><span className="journey-index">03 <span>—</span> CONNECT</span><div className="journey-graphic journey-graphic-three" aria-hidden="true"><ArrowUpRight size={86} strokeWidth={1.15} /></div><h3>Let's talk details</h3><p>Reach out so we can discuss the right product options for your team.</p></div></div><Link href="/contact" className="text-link journey-link">Start your inquiry <ArrowUpRight size={18} /></Link></div></section>

    <section className="section value-section container"><div className="section-kicker"><span className="tiny-square" /> THE TABEER APPROACH</div><div className="value-grid"><div className="value-card"><span className="value-number">01</span><Users size={31} strokeWidth={1.5} /><h3>Made for teams</h3><p>Coordinate your look across players, coaches and staff.</p></div><div className="value-card"><span className="value-number">02</span><Sparkles size={31} strokeWidth={1.5} /><h3>Made to stand out</h3><p>Build a memorable identity through custom colors and details.</p></div><div className="value-card"><span className="value-number">03</span><ShieldCheck size={31} strokeWidth={1.5} /><h3>Made for the moment</h3><p>Get ready for training days, game days and everything between.</p></div></div></section>

    <section className="section faq-section"><div className="container faq-grid"><div className="faq-intro"><div className="section-kicker"><span className="tiny-square" /> GOOD TO KNOW</div><h2 className="display-heading">YOUR<br />QUESTIONS<span>.</span><br />ANSWERED.</h2><p>Have something specific in mind? We are one message away.</p><Link href="/contact" className="text-link">Ask us anything <ArrowUpRight size={18} /></Link></div><div className="faq-list"><details><summary><span>01</span> Can we discuss custom team colors and details? <Plus size={20} /></summary><p>Yes. Share your colors, logo, names or numbers in your inquiry and tell us which product you are interested in. We can discuss the available options with you.</p></details><details><summary><span>02</span> Which sports do you cover? <Plus size={20} /></summary><p>Our range includes soccer, American football, basketball, baseball, ice hockey, polo and BJJ, along with team apparel and equipment. Explore the full product collection for details.</p></details><details><summary><span>03</span> How do I ask about sizing or quantities? <Plus size={20} /></summary><p>Send us the product, the sizes you need and an estimated quantity through the contact page. We will continue the conversation directly.</p></details><details><summary><span>04</span> How do I start an inquiry? <Plus size={20} /></summary><p>Choose a product and use its inquiry button, or use the contact form to prepare a WhatsApp message with your requirements.</p></details></div></div></section>

    <section className="contact-banner"><div className="container contact-banner-inner"><div><span className="eyebrow">HAVE A TEAM IN MIND?</span><h2>LET'S MAKE IT<br />HAPPEN<span>.</span></h2></div><Link href="/contact" className="banner-link">Let's talk about your project <MoveUpRight size={26} /></Link></div></section>
  </>;
}
